/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WrittenWorksIndexRouteImport } from './routes/written-works/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as WrittenWorksWrittenWorkIdRouteImport } from './routes/written-works/$writtenWorkId'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors/$authorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WrittenWorksIndexRoute = WrittenWorksIndexRouteImport.update({
  id: '/written-works/',
  path: '/written-works/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const WrittenWorksWrittenWorkIdRoute =
  WrittenWorksWrittenWorkIdRouteImport.update({
    id: '/written-works/$writtenWorkId',
    path: '/written-works/$writtenWorkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/written-works/$writtenWorkId': typeof WrittenWorksWrittenWorkIdRoute
  '/about': typeof AboutIndexRoute
  '/authors': typeof AuthorsIndexRoute
  '/written-works': typeof WrittenWorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/written-works/$writtenWorkId': typeof WrittenWorksWrittenWorkIdRoute
  '/about': typeof AboutIndexRoute
  '/authors': typeof AuthorsIndexRoute
  '/written-works': typeof WrittenWorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/written-works/$writtenWorkId': typeof WrittenWorksWrittenWorkIdRoute
  '/about/': typeof AboutIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/written-works/': typeof WrittenWorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors/$authorId'
    | '/written-works/$writtenWorkId'
    | '/about'
    | '/authors'
    | '/written-works'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authors/$authorId'
    | '/written-works/$writtenWorkId'
    | '/about'
    | '/authors'
    | '/written-works'
  id:
    | '__root__'
    | '/'
    | '/authors/$authorId'
    | '/written-works/$writtenWorkId'
    | '/about/'
    | '/authors/'
    | '/written-works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  WrittenWorksWrittenWorkIdRoute: typeof WrittenWorksWrittenWorkIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  WrittenWorksIndexRoute: typeof WrittenWorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/written-works/': {
      id: '/written-works/'
      path: '/written-works'
      fullPath: '/written-works'
      preLoaderRoute: typeof WrittenWorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/written-works/$writtenWorkId': {
      id: '/written-works/$writtenWorkId'
      path: '/written-works/$writtenWorkId'
      fullPath: '/written-works/$writtenWorkId'
      preLoaderRoute: typeof WrittenWorksWrittenWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  WrittenWorksWrittenWorkIdRoute: WrittenWorksWrittenWorkIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  WrittenWorksIndexRoute: WrittenWorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
