// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919232621_RemoveAuthenticationFeature")]
    partial class RemoveAuthenticationFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Server.Models.Author", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("生年月日");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("没年月日");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT")
                        .HasColumnName("名");

                    b.Property<string>("GivenNameReading")
                        .HasColumnType("TEXT")
                        .HasColumnName("名読み");

                    b.Property<string>("GivenNameRomaji")
                        .HasColumnType("TEXT")
                        .HasColumnName("名ローマ字");

                    b.Property<string>("GivenNameSort")
                        .HasColumnType("TEXT")
                        .HasColumnName("名読みソート用");

                    b.Property<bool>("PersonalityRights")
                        .HasColumnType("INTEGER")
                        .HasColumnName("人物著作権フラグ");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("姓");

                    b.Property<string>("SurnameReading")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("姓読み");

                    b.Property<string>("SurnameRomaji")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("姓ローマ字");

                    b.Property<string>("SurnameSort")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("姓読みソート用");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Server.Models.Publisher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("出版社名");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Server.Models.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("底本名");

                    b.Property<string>("OriginalSourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("底本の親元ID");

                    b.Property<string>("PublishDateInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("底本出版社発行年");

                    b.Property<string>("PublisherId")
                        .HasColumnType("TEXT")
                        .HasColumnName("底本出版社ID");

                    b.HasKey("Id");

                    b.HasIndex("OriginalSourceId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Server.Models.WriterRole", b =>
                {
                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("役割フラグ");

                    b.HasKey("Role");

                    b.ToTable("WriterRoles");
                });

            modelBuilder.Entity("Server.Models.WritingStyle", b =>
                {
                    b.Property<string>("Style")
                        .HasColumnType("TEXT")
                        .HasColumnName("文字使い種別");

                    b.HasKey("Style");

                    b.ToTable("WritingStyles");
                });

            modelBuilder.Entity("Server.Models.WrittenWork", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("人物ID");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("原題");

                    b.Property<string>("ReleaseInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("初出");

                    b.Property<string>("Source2Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("底本2ID");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("底本ID");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("副題");

                    b.Property<string>("SubtitleReading")
                        .HasColumnType("TEXT")
                        .HasColumnName("副題読み");

                    b.Property<string>("TextLink")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("テキストファイルURL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("作品名");

                    b.Property<string>("TitleReading")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("作品名読み");

                    b.Property<string>("TitleSort")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ソート用読み");

                    b.Property<bool>("WorkCopyright")
                        .HasColumnType("INTEGER")
                        .HasColumnName("作品著作権フラグ");

                    b.Property<string>("WriterRoleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("役割フラグID");

                    b.Property<string>("WritingStyleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("文字使い種別ID");

                    b.Property<string>("XHTMLLink")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("XHTML/HTMLファイルURL");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Source2Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("WriterRoleId");

                    b.HasIndex("WritingStyleId");

                    b.ToTable("WrittenWorks");
                });

            modelBuilder.Entity("Server.Models.Source", b =>
                {
                    b.HasOne("Server.Models.Source", "OriginalSource")
                        .WithMany("Sources")
                        .HasForeignKey("OriginalSourceId");

                    b.HasOne("Server.Models.Publisher", "Publisher")
                        .WithMany("Sources")
                        .HasForeignKey("PublisherId");

                    b.Navigation("OriginalSource");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Server.Models.WrittenWork", b =>
                {
                    b.HasOne("Server.Models.Author", "Author")
                        .WithMany("WrittenWorks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Source", "Source2")
                        .WithMany("WrittenWorks2")
                        .HasForeignKey("Source2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.Source", "Source")
                        .WithMany("WrittenWorks")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.WriterRole", "WriterRole")
                        .WithMany("WrittenWorks")
                        .HasForeignKey("WriterRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.WritingStyle", "WritingStyle")
                        .WithMany("WrittenWorks")
                        .HasForeignKey("WritingStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Source");

                    b.Navigation("Source2");

                    b.Navigation("WriterRole");

                    b.Navigation("WritingStyle");
                });

            modelBuilder.Entity("Server.Models.Author", b =>
                {
                    b.Navigation("WrittenWorks");
                });

            modelBuilder.Entity("Server.Models.Publisher", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Server.Models.Source", b =>
                {
                    b.Navigation("Sources");

                    b.Navigation("WrittenWorks");

                    b.Navigation("WrittenWorks2");
                });

            modelBuilder.Entity("Server.Models.WriterRole", b =>
                {
                    b.Navigation("WrittenWorks");
                });

            modelBuilder.Entity("Server.Models.WritingStyle", b =>
                {
                    b.Navigation("WrittenWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
