// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250903113109_UpdateAuthorsTable")]
    partial class UpdateAuthorsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("生年月日");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("没年月日");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT")
                        .HasColumnName("名");

                    b.Property<string>("GivenNameReading")
                        .HasColumnType("TEXT")
                        .HasColumnName("名読み");

                    b.Property<string>("GivenNameRomaji")
                        .HasColumnType("TEXT")
                        .HasColumnName("名ローマ字");

                    b.Property<string>("GivenNameSort")
                        .HasColumnType("TEXT")
                        .HasColumnName("名読みソート用");

                    b.Property<bool?>("PersonalityRights")
                        .HasColumnType("INTEGER")
                        .HasColumnName("人物著作権フラグ");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT")
                        .HasColumnName("姓");

                    b.Property<string>("SurnameReading")
                        .HasColumnType("TEXT")
                        .HasColumnName("姓読み");

                    b.Property<string>("SurnameRomaji")
                        .HasColumnType("TEXT")
                        .HasColumnName("姓ローマ字");

                    b.Property<string>("SurnameSort")
                        .HasColumnType("TEXT")
                        .HasColumnName("姓読みソート用");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
