// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Server.Models.Author", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenNameReading")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenNameRomaji")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenNameSort")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PersonalityRights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SurnameReading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SurnameRomaji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SurnameSort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Server.Models.Publisher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Server.Models.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishDateInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublisherId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalSourceId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Server.Models.WriterRole", b =>
                {
                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Role");

                    b.ToTable("WriterRoles");
                });

            modelBuilder.Entity("Server.Models.WritingStyle", b =>
                {
                    b.Property<string>("Style")
                        .HasColumnType("TEXT");

                    b.HasKey("Style");

                    b.ToTable("WritingStyles");
                });

            modelBuilder.Entity("Server.Models.WrittenWork", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HTMLLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source2Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleReading")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleReading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleSort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WorkCopyright")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WriterRoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WritingStyleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Source2Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("WriterRoleId");

                    b.HasIndex("WritingStyleId");

                    b.ToTable("WrittenWorks");
                });

            modelBuilder.Entity("Server.Models.Source", b =>
                {
                    b.HasOne("Server.Models.Source", "OriginalSource")
                        .WithMany("Sources")
                        .HasForeignKey("OriginalSourceId");

                    b.HasOne("Server.Models.Publisher", "Publisher")
                        .WithMany("Sources")
                        .HasForeignKey("PublisherId");

                    b.Navigation("OriginalSource");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Server.Models.WrittenWork", b =>
                {
                    b.HasOne("Server.Models.Author", "Author")
                        .WithMany("WrittenWorks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Source", "Source2")
                        .WithMany("WrittenWorks2")
                        .HasForeignKey("Source2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.Source", "Source")
                        .WithMany("WrittenWorks")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.WriterRole", "WriterRole")
                        .WithMany("WrittenWorks")
                        .HasForeignKey("WriterRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.WritingStyle", "WritingStyle")
                        .WithMany("WrittenWorks")
                        .HasForeignKey("WritingStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Source");

                    b.Navigation("Source2");

                    b.Navigation("WriterRole");

                    b.Navigation("WritingStyle");
                });

            modelBuilder.Entity("Server.Models.Author", b =>
                {
                    b.Navigation("WrittenWorks");
                });

            modelBuilder.Entity("Server.Models.Publisher", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Server.Models.Source", b =>
                {
                    b.Navigation("Sources");

                    b.Navigation("WrittenWorks");

                    b.Navigation("WrittenWorks2");
                });

            modelBuilder.Entity("Server.Models.WriterRole", b =>
                {
                    b.Navigation("WrittenWorks");
                });

            modelBuilder.Entity("Server.Models.WritingStyle", b =>
                {
                    b.Navigation("WrittenWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
